In [7]:
import pandas as pd
import numpy as np

In [8]:
df1=pd.read_excel('/content/uncleaned_data.xlsx')
df=df1.copy()

In [9]:
#1.	Identify and remove duplicate Item_ID rows
df.drop_duplicates(subset=['Item_ID'],keep='first',inplace=True)
df

,Item_ID,Batch_ID,Production_Date,Units_Produced,Defect_Count,Factory,Supervisor,Machine_ID,Shift,Quality_Fail_Flag,...,Operator_ID,Email,Supplier_ID,Shipping_ID,Root_Cause_ID,Maintenance_ID,Traceability_Record,Temp_Debug,Test_Col1,Test_Col2
0,ITEM1039,BATCH11098,2023-09-29 00:00:00,1391.0,NaN,Facotry C,Kumar,MC4135,Afternoon,1.0,...,OP171,op17179@ops.com,NaN,NaN,NaN,MT737,1.0,NaN,t1,NaN
1,ITEM1181,BATCH10323,12/31/2020,NaN,26.0,Factory A,NaN,MC7084,Night,NaN,...,OP300,op300@factory,NaN,NaN,NaN,NaN,0.0,NaN,t1,NaN
2,ITEM1036,BATCH11037,2020-08-01 00:00:00,NaN,414.0,Factory C,NaN,MC3719,night,NaN,...,OP872,op87281@ops.com,S994,SH6908,RC66,MT634,1.0,NaN,t1,NaN
3,ITEM1124,BATCH11579,2021-06-29 00:00:00,NaN,NaN,Factory A,NaN,MC8580,Afternoon,NaN,...,OP496,NaN,S158,SH4481,RC27,NaN,1.0,NaN,NaN,t2
4,ITEM1186,BATCH11011,NaN,2228.0,124.0,NaN,Priya,MC5216,Morning,NaN,...,NaN,16@ops.com,S306,NaN,NaN,MT738,0.0,debug,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,ITEM1069,BATCH11491,2024-05-10 00:00:00,NaN,147.0,NaN,Priya,NaN,Morn,NaN,...,OP701,op70193@gmail.com,NaN,SH6241,RC66,MT512,NaN,debug,NaN,NaN
759,ITEM1164,BATCH11895,2021-07-26 00:00:00,4473.0,NaN,Factory C,Anu,MC6617,Afternoon,NaN,...,OP486,op48621@gmail.com,S911,NaN,NaN,MT584,0.0,NaN,NaN,t2
835,ITEM1099,BATCH10644,2021-01-16 00:00:00,NaN,NaN,Factory A,NaN,NaN,Afternoon,0.0,...,OP135,op13542@ops.com,NaN,SH4239,NaN,NaN,1.0,NaN,t1,t2
1080,ITEM1041,BATCH10473,NaN,NaN,187.0,Factory B,NaN,MC8812,night,1.0,...,OP530,op53024@factory.com,S739,NaN,RC43,MT870,NaN,NaN,NaN,NaN
1381,ITEM1148,BATCH10974,2024-09-15 00:00:00,4617.0,NaN,Factory A,Priya,MC1380,night,0.0,...,OP957,op95745@gmail.com,NaN,SH6148,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#2.	Identify duplicate production batch IDs
df['Batch_ID'].duplicated().value_counts()

Batch_ID
False    189
True      11
Name: count, dtype: int64

In [11]:
#3.	Fill missing Units_Produced with median per item
x=df['Units_Produced'].median()
df['Units_Produced']=df['Units_Produced'].fillna(x)
df['Units_Produced']

0       1391.0
1       4002.0
2       4002.0
3       4002.0
4       2228.0
         ...
755     4002.0
759     4473.0
835     4002.0
1080    4002.0
1381    4617.0
Name: Units_Produced, Length: 200, dtype: float64

In [12]:
#4.	Fill missing Defect_Count with 0 or median.
df['Defect_Count']=df['Defect_Count'].fillna(0)
df['Defect_Count']

0         0.0
1        26.0
2       414.0
3         0.0
4       124.0
        ...
755     147.0
759       0.0
835       0.0
1080    187.0
1381      0.0
Name: Defect_Count, Length: 200, dtype: float64

In [13]:
#5.	Fill missing Factory with "Unknown Factory
df['Factory']=df['Factory'].fillna('unknown factory')
df['Factory']

0             Facotry C
1             Factory A
2             Factory C
3             Factory A
4       unknown factory
             ...
755     unknown factory
759           Factory C
835           Factory A
1080          Factory B
1381          Factory A
Name: Factory, Length: 200, dtype: object

In [14]:
#6.	Replace missing Supervisor with "Unassigned
df['Supervisor']=df['Supervisor'].fillna('unassigned')
df['Supervisor']

0            Kumar
1       unassigned
2       unassigned
3       unassigned
4            Priya
           ...
755          Priya
759            Anu
835     unassigned
1080    unassigned
1381         Priya
Name: Supervisor, Length: 200, dtype: object

In [15]:
#7.	Fill missing Production_Date with NaT or inferred date
df['Production_Date']=pd.to_datetime(df['Production_Date'],errors='coerce')
df['Production_Date']=df['Production_Date'].ffill()
df['Production_Date']

0      2023-09-29
1      2020-12-31
2      2020-08-01
3      2021-06-29
4      2021-06-29
          ...
755    2024-05-10
759    2021-07-26
835    2021-01-16
1080   2021-01-16
1381   2024-09-15
Name: Production_Date, Length: 200, dtype: datetime64[ns]

In [16]:
#8.	Fill missing Machine_ID with "Unknown Machine".
df['Machine_ID']=df['Machine_ID'].fillna('unknown Machine')
df['Machine_ID']

0                MC4135
1                MC7084
2                MC3719
3                MC8580
4                MC5216
             ...
755     unknown Machine
759              MC6617
835     unknown Machine
1080             MC8812
1381             MC1380
Name: Machine_ID, Length: 200, dtype: object

In [17]:
#9.	Replace missing Shift with "Unknown
df['Shift']=df['Shift'].fillna('unknown')
df['Shift']

0       Afternoon
1           Night
2           night
3       Afternoon
4         Morning
          ...
755          Morn
759     Afternoon
835     Afternoon
1080        night
1381        night
Name: Shift, Length: 200, dtype: object

In [18]:
#10.	Fill missing Email with "noemail@factory.com
df['Email']=df['Email'].fillna('noemail@factory.com')
df['Email']

0           op17179@ops.com
1             op300@factory
2           op87281@ops.com
3       noemail@factory.com
4                16@ops.com
               ...
755       op70193@gmail.com
759       op48621@gmail.com
835         op13542@ops.com
1080    op53024@factory.com
1381      op95745@gmail.com
Name: Email, Length: 200, dtype: object

In [19]:
#1.	Remove rows where Units_Produced <= 0
for i in df.index:
    if df.loc[i,'Units_Produced']<=0:
        df.drop(i,inplace=True)
df['Units_Produced']

0       1391.0
1       4002.0
2       4002.0
3       4002.0
4       2228.0
         ...
755     4002.0
759     4473.0
835     4002.0
1080    4002.0
1381    4617.0
Name: Units_Produced, Length: 200, dtype: float64

In [20]:
#2.	Remove rows with negative Defect_Count
for i in df.index:
    if df.loc[i,'Defect_Count']<=0:
        df.drop(i,inplace=True)
df['Defect_Count']

1        26.0
2       414.0
4       124.0
5       136.0
6       392.0
        ...
685     375.0
701      62.0
722     146.0
755     147.0
1080    187.0
Name: Defect_Count, Length: 122, dtype: float64

In [21]:
#5.	Correct typos in Factory names.
df['Factory']=df['Factory'].replace({'Facotry C':'Factory C','factory a':'Factory A'})
df['Factory']

1             Factory A
2             Factory C
4       unknown factory
5             Factory C
6             Factory A
             ...
685           Factory B
701     unknown factory
722           Factory A
755     unknown factory
1080          Factory B
Name: Factory, Length: 122, dtype: object

In [22]:
#7.	Standardize Shift values (Morning/Afternoon/Night
df['Shift']=df['Shift'].replace({'Aft':'Afternoon','Morn':'Morning','night':'Night'})
df['Shift'].value_counts()

Shift
Night        43
Afternoon    40
Morning      39
Name: count, dtype: int64

In [23]:
#8.	Remove invalid Machine_ID formats
for i in df.index:
    if df.loc[i,'Machine_ID']=='MACH-XYZ':
        df.drop(i,inplace=True)
df['Machine_ID']

1                MC7084
2                MC3719
4                MC5216
5                MC1969
6                MC5210
             ...
685              MC2486
701              MC2244
722              MC4379
755     unknown Machine
1080             MC8812
Name: Machine_ID, Length: 116, dtype: object

In [24]:
#3.	Fetch runs in a specific factory
dept=int(input('choose  the factory:{Factory A:1, Factory B:2, Factory C :3}\n '))
if dept ==1:
  print(df[df['Factory']=='Factory A'])

elif dept ==2:
  print(df[df['Factory']=='Factory B'])

elif dept ==3:
  print(df[df['Factory']=='Factory C'])

elif dept ==4:
  print(df[df['Factory']=='unknown factory'])
else:
    print('invalid choice')

choose  the factory:{Factory A:1, Factory B:2, Factory C :3}
 1
      Item_ID    Batch_ID Production_Date  Units_Produced  Defect_Count  \
1    ITEM1181  BATCH10323      2020-12-31          4002.0          26.0
6    ITEM1033  BATCH10604      2021-01-20          4002.0         392.0
19   ITEM1151  BATCH10595      2023-07-20          2542.0         429.0
20   ITEM1081  BATCH10738      2023-07-20          4002.0         147.0
24   ITEM1010  BATCH10024      2020-06-01          3849.0         398.0
27   ITEM1054  BATCH11068      2025-04-15          4002.0          83.0
32   ITEM1021  BATCH10396      2023-02-01          4581.0         191.0
33   ITEM1126  BATCH10879      2022-01-17         16999.0         475.0
40   ITEM1037  BATCH10284      2020-11-24          4897.0         202.0
44   ITEM1065  BATCH11380      2024-09-10          4002.0         492.0
51   ITEM1125  BATCH11529      2025-01-12          4002.0          34.0
53   ITEM1003  BATCH10037      2021-12-17          4032.0          65.0
54   ITEM1078  BATCH10601      2020-10-10          4002.0          49.0
60   ITEM1015  BATCH11255      2022-03-11          3809.0          63.0
62   ITEM1197  BATCH11305      2025-01-30          2794.0          13.0
64   ITEM1045  BATCH10267      2025-05-28          1395.0         437.0
71   ITEM1179  BATCH10738      2022-08-03          4368.0         309.0
77   ITEM1053  BATCH11117      2022-05-05         14451.0          58.0
78   ITEM1130  BATCH10101      2022-05-05          2789.0         177.0
93   ITEM1095  BATCH10851      2024-08-31          4002.0          19.0
98   ITEM1056  BATCH11516      2020-02-10          5117.0         390.0
104  ITEM1057  BATCH10203      2020-02-01          7773.0         115.0
111  ITEM1027  BATCH11016      2024-05-14          2333.0           9.0
129  ITEM1155  BATCH10099      2022-05-18            19.0         493.0
148  ITEM1162  BATCH11387      2024-01-25            55.0           8.0
155  ITEM1185  BATCH11028      2023-03-13          4002.0          73.0
175  ITEM1104  BATCH11857      2022-05-03          4002.0         202.0
195  ITEM1083  BATCH11362      2021-12-27          4002.0         150.0
216  ITEM1116  BATCH11191      2021-10-18         18898.0         368.0
222  ITEM1178  BATCH10163      2020-05-13          4002.0         199.0
228  ITEM1196  BATCH11409      2020-06-18          3275.0         288.0
236  ITEM1076  BATCH10083      2024-02-27          4002.0          38.0
239  ITEM1107  BATCH10777      2022-04-30          3050.0         351.0
250  ITEM1161  BATCH10580      2024-02-14          4576.0         134.0
251  ITEM1023  BATCH10714      2020-04-01          2146.0          39.0
275  ITEM1071  BATCH11822      2024-03-07          4002.0         303.0
314  ITEM1188  BATCH11577      2020-01-29          3853.0         226.0
357  ITEM1017  BATCH11985      2024-07-06           168.0          70.0
385  ITEM1113  BATCH10985      2024-05-29          4002.0         448.0
391  ITEM1198  BATCH10031      2021-04-21          4002.0         436.0
428  ITEM1137  BATCH10247      2021-12-14          4002.0         280.0
431  ITEM1007  BATCH11022      2024-10-30          1709.0         178.0
604  ITEM1011  BATCH10393      2022-10-18         12928.0         417.0
722  ITEM1079  BATCH11688      2022-08-09          4002.0         146.0

       Factory  Supervisor       Machine_ID      Shift  Quality_Fail_Flag  \
1    Factory A  unassigned           MC7084      Night                NaN
6    Factory A  unassigned           MC5210    Morning                1.0
19   Factory A  unassigned           MC6769      Night                NaN
20   Factory A       Kumar           MC8025    Morning                NaN
24   Factory A  unassigned           MC1009    Morning                0.0
27   Factory A         Anu           MC2314  Afternoon                0.0
32   Factory A         Anu  unknown Machine  Afternoon                NaN
33   Factory A       Kumar           MC9090      Night                0.0
40   Factory A         Anu           MC1166    Morning                1.0
44   Factory A         Anu           MC5290      Night                0.0
51   Factory A       Kumar           MC5468  Afternoon                NaN
53   Factory A      Ramesh           MC4155  Afternoon                1.0
54   Factory A       Priya           MC9593    Morning                0.0
60   Factory A       Kumar           MC3042      Night                1.0
62   Factory A  unassigned           MC4360      Night                NaN
64   Factory A  unassigned           MC9196      Night                1.0
71   Factory A       Priya  unknown Machine      Night                0.0
77   Factory A       Priya           MC8182  Afternoon                1.0
78   Factory A       Kumar  unknown Machine    Morning                0.0
93   Factory A      Ramesh           MC6582    Morning                NaN
98   Factory A       Kumar           MC6378  Afternoon                NaN
104  Factory A       Kumar           MC6955  Afternoon                1.0
111  Factory A  unassigned           MC3549      Night                NaN
129  Factory A  unassigned           MC6125      Night                NaN
148  Factory A         Anu           MC5992  Afternoon                NaN
155  Factory A  unassigned           MC7122      Night                0.0
175  Factory A       Priya           MC5126  Afternoon                1.0
195  Factory A  unassigned           MC8825  Afternoon                0.0
216  Factory A  unassigned           MC9901    Morning                NaN
222  Factory A       Priya           MC7474  Afternoon                1.0
228  Factory A       Kumar           MC5452  Afternoon                1.0
236  Factory A      Ramesh           MC9030      Night                1.0
239  Factory A  unassigned           MC4970    Morning                1.0
250  Factory A  unassigned  unknown Machine    Morning                NaN
251  Factory A      Ramesh           MC6220      Night                1.0
275  Factory A  unassigned           MC4951    Morning                1.0
314  Factory A       Priya           MC9361    Morning                1.0
357  Factory A  unassigned           MC1925  Afternoon                0.0
385  Factory A      Ramesh           MC2246  Afternoon                NaN
391  Factory A  unassigned           MC9089      Night                NaN
428  Factory A  unassigned           MC2071  Afternoon                1.0
431  Factory A      Ramesh           MC9970  Afternoon                NaN
604  Factory A       Kumar           MC7640      Night                1.0
722  Factory A      Ramesh           MC4379      Night                NaN

     ... Operator_ID                Email  Supplier_ID  Shipping_ID  \
1    ...       OP300        op300@factory          NaN          NaN
6    ...       OP966  op96651@factory.com          NaN          NaN
19   ...       OP734   op7346@factory.com         S624       SH2774
20   ...       OP255      op25550@ops.com          NaN          NaN
24   ...       OP785      op78579@ops.com          NaN          NaN
27   ...       OP407  op40730@factory.com         S393          NaN
32   ...       OP918      op91851@ops.com          NaN          NaN
33   ...       OP652        op652@factory         S103       SH3347
40   ...       OP757      op75738@ops.com          NaN       SH1698
44   ...       OP671    op67182@gmail.com          NaN          NaN
51   ...       OP230    op23096@gmail.com         S143          NaN
53   ...       OP827      op82767@ops.com          NaN          NaN
54   ...       OP211  op21112@factory.com          NaN          NaN
60   ...       OP933  op93386@factory.com          NaN       SH1658
62   ...       OP802    op80242@gmail.com          NaN       SH2895
64   ...       OP682      op68256@ops.com         S747       SH9714
71   ...       OP657     op6573@gmail.com          NaN       SH4828
77   ...       OP968  op96866@factory.com          NaN          NaN
78   ...       OP605  op60510@factory.com          NaN          NaN
93   ...       OP407    op40790@gmail.com          NaN          NaN
98   ...         NaN           33@ops.com          NaN          NaN
104  ...       OP398  op39837@factory.com          NaN          NaN
111  ...       OP473  op47310@factory.com          NaN          NaN
129  ...       OP474    op47482@gmail.com          NaN       SH7270
148  ...       OP285       op2857@ops.com          NaN          NaN
155  ...       OP233  op23340@factory.com          NaN       SH3347
175  ...       OP438  op43891@factory.com         S412          NaN
195  ...       OP640      op64027@ops.com          NaN       SH2560
216  ...       OP383  op38316@factory.com         S840       SH8301
222  ...       OP296  op29664@factory.com         S929          NaN
228  ...       OP437  noemail@factory.com          NaN          NaN
236  ...       OP931    op93186@gmail.com          NaN          NaN
239  ...       OP756    op75647@gmail.com         S946       SH8012
250  ...       OP849  noemail@factory.com          NaN          NaN
251  ...       OP334  noemail@factory.com          NaN       SH1769
275  ...       OP438      op43830@ops.com         S384          NaN
314  ...       OP305  op30593@factory.com         S592          NaN
357  ...       OP667   op6672@factory.com          NaN          NaN
385  ...       OP216  noemail@factory.com         S370       SH9274
391  ...       OP860  op86090@factory.com         S296          NaN
428  ...       OP462      op46225@ops.com          NaN          NaN
431  ...       OP977  op97767@factory.com          NaN       SH9555
604  ...       OP696    op69624@gmail.com         S533          NaN
722  ...       OP735  op73596@factory.com          NaN          NaN

    Root_Cause_ID  Maintenance_ID  Traceability_Record  Temp_Debug  Test_Col1  \
1             NaN             NaN                  0.0         NaN         t1
6             NaN             NaN                  0.0         NaN         t1
19            NaN             NaN                  1.0         NaN        NaN
20            NaN           MT245                  NaN         NaN        NaN
24            NaN             NaN                  0.0         NaN        NaN
27            NaN             NaN                  0.0         NaN         t1
32            NaN             NaN                  1.0       debug        NaN
33           RC74           MT967                  0.0       debug         t1
40           RC80           MT412                  1.0       debug        NaN
44            NaN           MT557                  NaN       debug         t1
51            NaN             NaN                  NaN         NaN        NaN
53           RC85           MT749                  1.0       debug        NaN
54            NaN           MT641                  NaN         NaN        NaN
60            NaN             NaN                  1.0         NaN         t1
62            NaN             NaN                  NaN       debug        NaN
64           RC97             NaN                  1.0       debug        NaN
71           RC93             NaN                  0.0         NaN         t1
77            NaN           MT988                  0.0         NaN        NaN
78            NaN           MT614                  0.0         NaN        NaN
93            NaN             NaN                  0.0       debug         t1
98            NaN             NaN                  1.0       debug         t1
104          RC40             NaN                  0.0         NaN         t1
111          RC77           MT823                  1.0         NaN        NaN
129           NaN             NaN                  NaN       debug        NaN
148          RC95           MT356                  1.0         NaN        NaN
155          RC92             NaN                  1.0         NaN         t1
175           NaN             NaN                  0.0         NaN         t1
195          RC74             NaN                  NaN       debug        NaN
216           NaN             NaN                  1.0         NaN        NaN
222           NaN           MT103                  1.0         NaN        NaN
228           NaN             NaN                  NaN       debug        NaN
236           NaN           MT167                  NaN         NaN        NaN
239           NaN             NaN                  NaN         NaN        NaN
250           NaN             NaN                  1.0         NaN        NaN
251          RC52             NaN                  0.0         NaN        NaN
275           NaN             NaN                  NaN         NaN        NaN
314          RC56             NaN                  NaN         NaN         t1
357           NaN             NaN                  1.0         NaN        NaN
385          RC28           MT335                  NaN       debug        NaN
391           NaN             NaN                  0.0         NaN        NaN
428          RC53             NaN                  1.0         NaN        NaN
431           NaN             NaN                  0.0       debug        NaN
604           NaN             NaN                  1.0         NaN         t1
722           NaN           MT414                  1.0         NaN        NaN

     Test_Col2
1          NaN
6          NaN
19          t2
20         NaN
24          t2
27         NaN
32          t2
33         NaN
40         NaN
44         NaN
51         NaN
53         NaN
54          t2
60         NaN
62          t2
64         NaN
71         NaN
77         NaN
78         NaN
93          t2
98          t2
104        NaN
111        NaN
129        NaN
148         t2
155        NaN
175         t2
195        NaN
216        NaN
222        NaN
228         t2
236        NaN
239        NaN
250        NaN
251        NaN
275        NaN
314        NaN
357         t2
385        NaN
391        NaN
428        NaN
431        NaN
604        NaN
722        NaN

[44 rows x 30 columns]

In [25]:
#4.	Fetch runs on a specific date range
u_date=input('choose  the date:{year:month:date}\n ')
u_data=pd.to_datetime(u_date,errors='coerce')
filter_date=df[df['Production_Date']==u_date]
if filter_date.empty:
    print('no data available for this date')
else:
    print(filter_date)

choose  the date:{year:month:date}
 20-09-03
no data available for this date

In [26]:
#5.	Fetch runs with missing supervisor
print(df[df['Supervisor']=='unassigned'].to_string())

       Item_ID    Batch_ID Production_Date  Units_Produced  Defect_Count          Factory  Supervisor       Machine_ID      Shift  Quality_Fail_Flag QC_Check_Status  Downtime  Cycle_Time  Production_Duration Material_Code  Material_Cost  Labor_Cost  Overhead_Cost  Total_Cost  Cost_per_Unit Operator_ID                Email Supplier_ID Shipping_ID Root_Cause_ID Maintenance_ID  Traceability_Record Temp_Debug Test_Col1 Test_Col2
1     ITEM1181  BATCH10323      2020-12-31          4002.0          26.0        Factory A  unassigned           MC7084      Night                NaN             NaN    361.56      469.46               269.89        MAT100       44566.89    10467.02        1517.59         NaN            NaN       OP300        op300@factory         NaN         NaN           NaN            NaN                  0.0        NaN        t1       NaN
2     ITEM1036  BATCH11037      2020-08-01          4002.0         414.0        Factory C  unassigned           MC3719      Night                NaN          Passed     42.51      373.71               851.06        MAT300       44962.26      297.26        8288.35         NaN            NaN       OP872      op87281@ops.com        S994      SH6908          RC66          MT634                  1.0        NaN        t1       NaN
5     ITEM1020  BATCH11244      2023-11-17          1196.0         136.0        Factory C  unassigned           MC1969  Afternoon                NaN          Failed    249.04       74.98               317.33       mat-500        5871.14    16165.00       14166.63    36202.77          30.27       OP734  noemail@factory.com         NaN         NaN           NaN            NaN                  1.0        NaN        t1       NaN
6     ITEM1033  BATCH10604      2021-01-20          4002.0         392.0        Factory A  unassigned           MC5210    Morning                1.0             NaN    401.14      233.10                75.30           NaN       48291.51    17202.81       10863.25         NaN            NaN       OP966  op96651@factory.com         NaN         NaN           NaN            NaN                  0.0        NaN        t1       NaN
13    ITEM1034  BATCH10306      2021-10-09          3577.0          95.0  unknown factory  unassigned           MC5591  Afternoon                0.0             NaN    332.34      183.26               180.77        MAT300        5792.02     1455.64        1144.56     8392.22           2.35       OP968  op96863@factory.com        S903      SH6882           NaN            NaN                  NaN      debug       NaN        t2
15    ITEM1193  BATCH11900      2022-03-02          3389.0         313.0  unknown factory  unassigned           MC7596    Morning                1.0             NaN     15.55      303.92               681.26       BADCODE       42589.41     3895.43       11684.68    58169.52          17.16         NaN         21@gmail.com         NaN         NaN          RC56            NaN                  NaN      debug       NaN       NaN
19    ITEM1151  BATCH10595      2023-07-20          2542.0         429.0        Factory A  unassigned           MC6769      Night                NaN             NaN    415.34       72.62               701.84        MAT300        7198.03    12240.90       12439.95    31878.88          12.54       OP734   op7346@factory.com        S624      SH2774           NaN            NaN                  1.0        NaN       NaN        t2
24    ITEM1010  BATCH10024      2020-06-01          3849.0         398.0        Factory A  unassigned           MC1009    Morning                0.0          Passed    129.08      240.30                66.09        MAT400       45671.84     3312.08       10089.18    59073.10          15.35       OP785      op78579@ops.com         NaN         NaN           NaN            NaN                  0.0        NaN       NaN        t2
42    ITEM1169  BATCH11355      2024-06-23          7740.0         406.0        Factory B  unassigned           MC2229    Morning                0.0             NaN    137.91      359.77                65.00       mat-500       22793.78    10856.07       10571.80    44221.65           5.71       OP638      op63850@ops.com         NaN      SH4619           NaN            NaN                  NaN        NaN       NaN        t2
61    ITEM1040  BATCH11817      2023-05-09          6487.0         183.0        Factory C  unassigned           MC4765    Morning                1.0             NaN     17.76       33.18               143.92        MAT400       14651.13     1148.35        9282.41    25081.89           3.87       OP658  noemail@factory.com         NaN      SH3543           NaN          MT246                  1.0        NaN       NaN        t2
62    ITEM1197  BATCH11305      2025-01-30          2794.0          13.0        Factory A  unassigned           MC4360      Night                NaN             NaN    197.90      310.22               539.76        MAT200       41318.95      771.92        1969.15    44060.02          15.77       OP802    op80242@gmail.com         NaN      SH2895           NaN            NaN                  NaN      debug       NaN        t2
64    ITEM1045  BATCH10267      2025-05-28          1395.0         437.0        Factory A  unassigned           MC9196      Night                1.0             NaN    466.26      214.06               319.54       mat-500       21075.70    10615.63        8680.07    40371.40          28.94       OP682      op68256@ops.com        S747      SH9714          RC97            NaN                  1.0      debug       NaN       NaN
103   ITEM1128  BATCH11885      2021-07-16          4002.0         103.0        Factory C  unassigned           MC3837    Morning                NaN             NaN    270.87      337.29               867.65       mat-500       31808.76    13866.27        9151.15         NaN            NaN       OP352    op35239@gmail.com        S821         NaN           NaN            NaN                  0.0        NaN       NaN       NaN
111   ITEM1027  BATCH11016      2024-05-14          2333.0           9.0        Factory A  unassigned           MC3549      Night                NaN          Passed    359.49      127.70               581.83        MAT300       42115.45    12722.65       12322.13    67160.23          28.79       OP473  op47310@factory.com         NaN         NaN          RC77          MT823                  1.0        NaN       NaN       NaN
114   ITEM1092  BATCH11197      2020-06-11          1904.0         250.0        Factory C  unassigned           MC3376      Night                0.0          Passed     93.04      317.53               475.30           NaN       26594.67     3286.33        4951.47    34832.47          18.29       OP714      op71418@ops.com         NaN         NaN          RC11            NaN                  1.0        NaN        t1       NaN
129   ITEM1155  BATCH10099      2022-05-18            19.0         493.0        Factory A  unassigned           MC6125      Night                NaN          Failed    417.53       92.31               955.11        MAT400        7101.12    18302.14        1863.00    27266.26        1435.07       OP474    op47482@gmail.com         NaN      SH7270           NaN            NaN                  NaN      debug       NaN       NaN
138   ITEM1160  BATCH11174      2021-06-08          4002.0           9.0        Factory C  unassigned  unknown Machine      Night                1.0             NaN    402.71      370.86                50.00        MAT100       22175.14      989.68       12365.69         NaN            NaN       OP136  op13677@factory.com        S460         NaN          RC55            NaN                  NaN      debug        t1       NaN
139   ITEM1153  BATCH11341      2022-11-15         12423.0         178.0        Factory B  unassigned           MC2468    Morning                1.0             NaN    109.37      104.96               519.70        MAT400       18583.94    19727.61       12300.55    50612.10           4.07       OP402      op40223@ops.com         NaN         NaN           NaN            NaN                  1.0      debug       NaN        t2
149   ITEM1008  BATCH11902      2023-08-03         12892.0          85.0        Factory C  unassigned           MC2157      Night                0.0             NaN     55.20      141.94               493.39        MAT400       38158.99    18362.98        7178.74    63700.71           4.94       OP299      op29986@ops.com         NaN         NaN           NaN            NaN                  NaN        NaN       NaN       NaN
155   ITEM1185  BATCH11028      2023-03-13          4002.0          73.0        Factory A  unassigned           MC7122      Night                0.0             NaN    430.42      467.39               480.22        MAT100        -743.22     7367.28        1995.13         NaN            NaN       OP233  op23340@factory.com         NaN      SH3347          RC92            NaN                  1.0        NaN        t1       NaN
157   ITEM1123  BATCH11025      2023-07-11          4002.0         189.0        Factory C  unassigned           MC5475  Afternoon                1.0             NaN    446.79      229.21               418.58        MAT400       32655.93     9920.68        5951.41         NaN            NaN       OP361    op36129@gmail.com         NaN         NaN           NaN          MT385                  1.0      debug        t1       NaN
164   ITEM1143  BATCH11799      2021-10-30          2961.0          93.0        Factory C  unassigned           MC5192      Night                NaN             NaN     23.89      483.50               669.70           NaN        2447.83     5866.45        6523.75    14838.03           5.01       OP958      op95838@ops.com         NaN         NaN           NaN            NaN                  NaN        NaN       NaN       NaN
165   ITEM1146  BATCH11671      2021-10-30          4002.0          35.0  unknown factory  unassigned           MC4648    Morning                NaN          Failed     29.75      252.99               178.79       mat-500       33506.36    16346.83        7885.72         NaN            NaN       OP112       op1125@ops.com        S939         NaN           NaN            NaN                  0.0        NaN       NaN       NaN
166   ITEM1182  BATCH11069      2021-10-30          4002.0         158.0        Factory C  unassigned  unknown Machine      Night                0.0             NaN     92.03       93.95               255.84        MAT300       30199.38    11671.86       11011.67         NaN            NaN       OP580    op58071@gmail.com        S752         NaN          RC61          MT156                  0.0      debug       NaN       NaN
195   ITEM1083  BATCH11362      2021-12-27          4002.0         150.0        Factory A  unassigned           MC8825  Afternoon                0.0             NaN     99.03      322.42               945.80       mat-500       31389.24    10930.58        9184.22         NaN            NaN       OP640      op64027@ops.com         NaN      SH2560          RC74            NaN                  NaN      debug       NaN       NaN
199   ITEM1149  BATCH11931      2025-03-09           498.0          71.0        Factory C  unassigned           MC7035  Afternoon                0.0             NaN     30.40      346.64               111.21        MAT400       16241.66    18185.44        3250.77    37677.87          75.66       OP220  op22061@factory.com        S309      SH9977          RC95            NaN                  0.0      debug       NaN       NaN
216   ITEM1116  BATCH11191      2021-10-18         18898.0         368.0        Factory A  unassigned           MC9901    Morning                NaN             NaN    237.41      127.52               244.94        MAT100         175.94    11934.50       12617.36    24727.80           1.31       OP383  op38316@factory.com        S840      SH8301           NaN            NaN                  1.0        NaN       NaN       NaN
235   ITEM1005  BATCH10136      2022-07-03          4002.0          47.0        Factory B  unassigned           MC6984  Afternoon                1.0          Failed    119.35      484.72               983.01       BADCODE       44779.26     2734.56         576.06         NaN            NaN       OP344       op3443@ops.com         NaN         NaN           NaN          MT781                  1.0        NaN       NaN       NaN
239   ITEM1107  BATCH10777      2022-04-30          3050.0         351.0        Factory A  unassigned           MC4970    Morning                1.0             NaN     41.02       32.57               614.93        MAT100       34761.38     8684.19        6298.34    49743.91          16.31       OP756    op75647@gmail.com        S946      SH8012           NaN            NaN                  NaN        NaN       NaN       NaN
250   ITEM1161  BATCH10580      2024-02-14          4576.0         134.0        Factory A  unassigned  unknown Machine    Morning                NaN          Failed    338.58      196.76               180.92        MAT100       14671.33    12505.76        9269.91    36447.00           7.96       OP849  noemail@factory.com         NaN         NaN           NaN            NaN                  1.0        NaN       NaN       NaN
252   ITEM1166  BATCH10967      2022-02-24          4002.0         191.0  unknown factory  unassigned           MC5251    Morning                NaN             NaN     58.12       48.77               688.18       BADCODE        7470.42     3177.18       11648.90         NaN            NaN       OP118      op11883@ops.com         NaN         NaN           NaN            NaN                  0.0        NaN        t1       NaN
275   ITEM1071  BATCH11822      2024-03-07          4002.0         303.0        Factory A  unassigned           MC4951    Morning                1.0             NaN    268.24      327.96               695.87        MAT100       46237.64     9790.99       14883.85         NaN            NaN       OP438      op43830@ops.com        S384         NaN           NaN            NaN                  NaN        NaN       NaN       NaN
327   ITEM1150  BATCH10537      2024-03-15          4549.0         154.0        Factory B  unassigned           MC2680      Night                NaN             NaN    367.93      123.69               792.59        MAT200       49477.18     5243.14        7526.94    62247.26          13.68       OP870       op8702@ops.com         NaN      SH8174           NaN            NaN                  1.0        NaN       NaN        t2
336   ITEM1100  BATCH10412      2023-08-24           750.0          92.0        Factory C  unassigned           MC3624  Afternoon                0.0          Passed     88.62      193.87               498.37        MAT300        -882.23    13802.62       12498.45    25418.84          33.89       OP452    op45216@gmail.com         NaN         NaN           NaN          MT194                  0.0      debug        t1       NaN
357   ITEM1017  BATCH11985      2024-07-06           168.0          70.0        Factory A  unassigned           MC1925  Afternoon                0.0             NaN    434.41       57.53               622.70        MAT300       26232.03    11354.66        6011.06    43597.75         259.51       OP667   op6672@factory.com         NaN         NaN           NaN            NaN                  1.0        NaN       NaN        t2
375   ITEM1138  BATCH10229      2024-05-29          1308.0         134.0        Factory C  unassigned           MC7268  Afternoon                NaN             NaN    332.14      275.06               493.51        MAT300       31705.81    11929.19       14939.22    58574.22          44.78       OP469  op46914@factory.com        S933         NaN           NaN          MT246                  NaN        NaN       NaN       NaN
391   ITEM1198  BATCH10031      2021-04-21          4002.0         436.0        Factory A  unassigned           MC9089      Night                NaN          Passed    183.21      426.10               397.51        MAT400       25134.71    14141.12         189.86         NaN            NaN       OP860  op86090@factory.com        S296         NaN           NaN            NaN                  0.0        NaN       NaN       NaN
401   ITEM1177  BATCH10076      2021-10-17          6622.0          44.0        Factory B  unassigned           MC5126  Afternoon                1.0          Failed    225.71      457.56               559.90        MAT200       33023.21    13461.17        5718.52    52202.90           7.88       OP816      op81661@ops.com         NaN      SH3662           NaN          MT452                  1.0        NaN       NaN       NaN
404   ITEM1044  BATCH10621      2022-02-08          2629.0          33.0        Factory C  unassigned           MC6478  Afternoon                NaN             NaN    441.14      344.78               574.36        MAT200       40283.61     2786.93        6654.09    49724.63          18.91       OP999   op9995@factory.com         NaN         NaN           NaN          MT577                  1.0      debug        t1        t2
428   ITEM1137  BATCH10247      2021-12-14          4002.0         280.0        Factory A  unassigned           MC2071  Afternoon                1.0             NaN    437.33      480.19               745.04        MAT300       46105.44     9460.13       14708.25         NaN            NaN       OP462      op46225@ops.com         NaN         NaN          RC53            NaN                  1.0        NaN       NaN       NaN
443   ITEM1127  BATCH10382      2020-04-20           725.0          11.0        Factory C  unassigned           MC1327  Afternoon                NaN             NaN    358.20       15.31               609.71       mat-500       29242.03     6352.02       14178.85    49772.90          68.65       OP517  noemail@factory.com        S788      SH4892          RC85            NaN                  0.0      debug       NaN       NaN
518   ITEM1109  BATCH11618      2024-01-14          4002.0         452.0  unknown factory  unassigned           MC3721      Night                0.0             NaN    197.45      483.24                32.46        MAT300       26697.11    19770.74        1417.51         NaN            NaN       OP769      op76944@ops.com         NaN         NaN          RC81            NaN                  NaN        NaN        t1        t2
630   ITEM1066  BATCH10088      2025-01-04           912.0         161.0        Factory C  unassigned           MC8548    Morning                0.0             NaN    430.26      376.02               887.80        MAT400       31482.09    13364.71        7826.46    52673.26          57.76       OP589      op58942@ops.com        S594         NaN           NaN            NaN                  NaN      debug       NaN       NaN
701   ITEM1074  BATCH10401      2022-03-15          4002.0          62.0  unknown factory  unassigned           MC2244    Morning                0.0          Failed    342.75      115.59               432.89        MAT300        2367.54    16257.52        8459.42         NaN            NaN       OP873  op87363@factory.com         NaN         NaN           NaN            NaN                  NaN      debug        t1        t2
1080  ITEM1041  BATCH10473      2021-01-16          4002.0         187.0        Factory B  unassigned           MC8812      Night                1.0             NaN    291.77       83.19               946.31       BADCODE       48842.44    18947.46        6635.30         NaN            NaN       OP530  op53024@factory.com        S739         NaN          RC43          MT870                  NaN        NaN       NaN       NaN

In [27]:
#6.	Fetch machines with unusually high downtime
print(df.groupby('Machine_ID')['Downtime'].max())

Machine_ID
MC1009             129.08
MC1057             242.03
MC1059              27.92
MC1086             269.17
MC1166             249.11
                    ...
MC9810             410.22
MC9901             237.41
MC9968             492.88
MC9970              87.34
unknown Machine    402.71
Name: Downtime, Length: 107, dtype: float64

In [28]:
#7.	Fetch batches with quality_fail flag
print(df.groupby('Batch_ID')['Quality_Fail_Flag'].value_counts())

Batch_ID    Quality_Fail_Flag
BATCH10019  0.0                  1
BATCH10024  0.0                  1
BATCH10026  1.0                  1
BATCH10037  1.0                  1
BATCH10042  0.0                  1
                                ..
BATCH11902  0.0                  1
BATCH11931  0.0                  1
BATCH11933  0.0                  1
BATCH11937  0.0                  1
BATCH11985  0.0                  1
Name: count, Length: 78, dtype: int64

In [29]:
#8.	Fetch runs with negative cycle time entries
print(df[df['Cycle_Time']<=0].to_string())

      Item_ID    Batch_ID Production_Date  Units_Produced  Defect_Count    Factory Supervisor Machine_ID      Shift  Quality_Fail_Flag QC_Check_Status  Downtime  Cycle_Time  Production_Duration Material_Code  Material_Cost  Labor_Cost  Overhead_Cost  Total_Cost  Cost_per_Unit Operator_ID                Email Supplier_ID Shipping_ID Root_Cause_ID Maintenance_ID  Traceability_Record Temp_Debug Test_Col1 Test_Col2
153  ITEM1080  BATCH11556      2024-11-17         10690.0         120.0  Factory B     Ramesh     MC1279  Afternoon                0.0             NaN    135.78       -1.58               113.35        MAT200       24662.54    13110.34        1901.59    39674.47           3.71       OP615  op61533@factory.com         NaN         NaN           NaN            NaN                  0.0        NaN        t1        t2
247  ITEM1170  BATCH10042      2024-03-16          3713.0         124.0  Factory C      Priya     MC2086    Morning                0.0             NaN    420.95       -1.02                11.99        MAT300        4636.78     2439.17        5043.42    12119.37           3.26       OP863       op8637@ops.com        S583         NaN           NaN            NaN                  NaN        NaN       NaN       NaN

In [30]:
#9.	Fetch runs in a particular shift.
u_shift=int(input('choose  the shift:{morning:1,afternoon:2,evening:3}:\n '))
if u_shift ==1:
    print(df[df['Shift']=='Morning'].to_string())
elif u_shift ==2:
    print(df[df['Shift']=='Afternoon'].to_string())
elif u_shift ==3:
    print(df[df['Shift']=='Night'].to_string())
else:
    print('invalid choice')

choose  the shift:{morning:1,afternoon:2,evening:3}:
 1
      Item_ID    Batch_ID Production_Date  Units_Produced  Defect_Count          Factory  Supervisor       Machine_ID    Shift  Quality_Fail_Flag QC_Check_Status  Downtime  Cycle_Time  Production_Duration Material_Code  Material_Cost  Labor_Cost  Overhead_Cost  Total_Cost  Cost_per_Unit Operator_ID                Email Supplier_ID Shipping_ID Root_Cause_ID Maintenance_ID  Traceability_Record Temp_Debug Test_Col1 Test_Col2
4    ITEM1186  BATCH11011      2021-06-29          2228.0         124.0  unknown factory       Priya           MC5216  Morning                NaN          Failed    400.15      156.93               558.77        MAT200       11073.57     2387.51        2345.81    15806.89           7.09         NaN           16@ops.com        S306         NaN           NaN          MT738                  0.0      debug       NaN       NaN
6    ITEM1033  BATCH10604      2021-01-20          4002.0         392.0        Factory A  unassigned           MC5210  Morning                1.0             NaN    401.14      233.10                75.30           NaN       48291.51    17202.81       10863.25         NaN            NaN       OP966  op96651@factory.com         NaN         NaN           NaN            NaN                  0.0        NaN        t1       NaN
15   ITEM1193  BATCH11900      2022-03-02          3389.0         313.0  unknown factory  unassigned           MC7596  Morning                1.0             NaN     15.55      303.92               681.26       BADCODE       42589.41     3895.43       11684.68    58169.52          17.16         NaN         21@gmail.com         NaN         NaN          RC56            NaN                  NaN      debug       NaN       NaN
18   ITEM1093  BATCH10689      2023-11-09           887.0         384.0        Factory C       Kumar           MC1086  Morning                NaN          Failed    269.17      380.79                60.56           NaN       46650.52     4454.81        5830.97    56936.30          64.19       OP274    op27467@gmail.com        S173      SH5341          RC18            NaN                  0.0        NaN       NaN        t2
20   ITEM1081  BATCH10738      2023-07-20          4002.0         147.0        Factory A       Kumar           MC8025  Morning                NaN          Passed     83.40      494.05               471.87        MAT300        3082.61     1260.62         184.81         NaN            NaN       OP255      op25550@ops.com         NaN         NaN           NaN          MT245                  NaN        NaN       NaN       NaN
24   ITEM1010  BATCH10024      2020-06-01          3849.0         398.0        Factory A  unassigned           MC1009  Morning                0.0          Passed    129.08      240.30                66.09        MAT400       45671.84     3312.08       10089.18    59073.10          15.35       OP785      op78579@ops.com         NaN         NaN           NaN            NaN                  0.0        NaN       NaN        t2
40   ITEM1037  BATCH10284      2020-11-24          4897.0         202.0        Factory A         Anu           MC1166  Morning                1.0          Failed    249.11      463.64               400.26        MAT100       12335.49    15269.30        7441.28    35046.07           7.16       OP757      op75738@ops.com         NaN      SH1698          RC80          MT412                  1.0      debug       NaN       NaN
42   ITEM1169  BATCH11355      2024-06-23          7740.0         406.0        Factory B  unassigned           MC2229  Morning                0.0             NaN    137.91      359.77                65.00       mat-500       22793.78    10856.07       10571.80    44221.65           5.71       OP638      op63850@ops.com         NaN      SH4619           NaN            NaN                  NaN        NaN       NaN        t2
54   ITEM1078  BATCH10601      2020-10-10          4002.0          49.0        Factory A       Priya           MC9593  Morning                0.0             NaN    220.90      157.29                16.06       BADCODE       12553.48    16932.10       10456.89         NaN            NaN       OP211  op21112@factory.com         NaN         NaN           NaN          MT641                  NaN        NaN       NaN        t2
61   ITEM1040  BATCH11817      2023-05-09          6487.0         183.0        Factory C  unassigned           MC4765  Morning                1.0             NaN     17.76       33.18               143.92        MAT400       14651.13     1148.35        9282.41    25081.89           3.87       OP658  noemail@factory.com         NaN      SH3543           NaN          MT246                  1.0        NaN       NaN        t2
78   ITEM1130  BATCH10101      2022-05-05          2789.0         177.0        Factory A       Kumar  unknown Machine  Morning                0.0          Passed     46.20      495.73               128.54        MAT100       10809.35      438.07        5930.19    17177.61           6.16       OP605  op60510@factory.com         NaN         NaN           NaN          MT614                  0.0        NaN       NaN       NaN
79   ITEM1090  BATCH11937      2024-03-05          4002.0         371.0  unknown factory         Anu           MC9781  Morning                0.0             NaN    491.25      269.57               822.37        MAT200       30544.94    18084.76       11006.09         NaN            NaN       OP988      op98835@ops.com        S401      SH4174           NaN            NaN                  NaN        NaN        t1       NaN
92   ITEM1070  BATCH11672      2020-11-29          2098.0          63.0        Factory C         Anu           MC6749  Morning                0.0             NaN    154.79      344.44               901.74        MAT400       38722.26     8717.50       12538.39    59978.15          28.59       OP319    op31997@gmail.com        S573      SH8587          RC32            NaN                  NaN      debug       NaN       NaN
93   ITEM1095  BATCH10851      2024-08-31          4002.0          19.0        Factory A      Ramesh           MC6582  Morning                NaN          Passed    392.00      318.32               246.04       BADCODE       40930.39     5869.03       12879.85         NaN            NaN       OP407    op40790@gmail.com         NaN         NaN           NaN            NaN                  0.0      debug        t1        t2
97   ITEM1120  BATCH11771      2022-05-22         18252.0         108.0  unknown factory       Kumar           MC1808  Morning                1.0             NaN    307.71      361.44               106.63        MAT300       43875.57    19597.43       13069.86    76542.86           4.19       OP785    op78515@gmail.com         NaN      SH7657           NaN            NaN                  0.0      debug        t1       NaN
103  ITEM1128  BATCH11885      2021-07-16          4002.0         103.0        Factory C  unassigned           MC3837  Morning                NaN             NaN    270.87      337.29               867.65       mat-500       31808.76    13866.27        9151.15         NaN            NaN       OP352    op35239@gmail.com        S821         NaN           NaN            NaN                  0.0        NaN       NaN       NaN
126  ITEM1172  BATCH11729      2022-11-07         18293.0          51.0  unknown factory       Kumar           MC9795  Morning                1.0             NaN    195.26      317.01               660.14       mat-500       11971.41    12280.52       14068.77    38320.70           2.09       OP831        op831@factory        S105      SH2797           NaN            NaN                  NaN        NaN        t1       NaN
139  ITEM1153  BATCH11341      2022-11-15         12423.0         178.0        Factory B  unassigned           MC2468  Morning                1.0             NaN    109.37      104.96               519.70        MAT400       18583.94    19727.61       12300.55    50612.10           4.07       OP402      op40223@ops.com         NaN         NaN           NaN            NaN                  1.0      debug       NaN        t2
165  ITEM1146  BATCH11671      2021-10-30          4002.0          35.0  unknown factory  unassigned           MC4648  Morning                NaN          Failed     29.75      252.99               178.79       mat-500       33506.36    16346.83        7885.72         NaN            NaN       OP112       op1125@ops.com        S939         NaN           NaN            NaN                  0.0        NaN       NaN       NaN
187  ITEM1028  BATCH10909      2025-05-01          4002.0         353.0  unknown factory       Kumar           MC5153  Morning                1.0          Failed     92.92      149.28               824.94       mat-500       47232.11    11937.10        4482.13         NaN            NaN       OP312      op31256@ops.com         NaN      SH1415          RC81          MT776                  0.0      debug        t1       NaN
216  ITEM1116  BATCH11191      2021-10-18         18898.0         368.0        Factory A  unassigned           MC9901  Morning                NaN             NaN    237.41      127.52               244.94        MAT100         175.94    11934.50       12617.36    24727.80           1.31       OP383  op38316@factory.com        S840      SH8301           NaN            NaN                  1.0        NaN       NaN       NaN
229  ITEM1019  BATCH10159      2021-12-20          4002.0         350.0        Factory C       Kumar           MC8376  Morning                NaN             NaN    383.59      390.29               643.99        MAT100       30709.85     3897.23        6721.32         NaN            NaN       OP614    op61481@gmail.com         NaN      SH8265           NaN          MT364                  0.0        NaN        t1        t2
234  ITEM1030  BATCH11498      2023-11-09          4327.0         151.0        Factory C      Ramesh           MC7307  Morning                1.0             NaN      1.32      335.45               449.28       mat-500        6101.74    17096.15        8244.36    31442.25           7.27       OP986      op98683@ops.com        S230         NaN           NaN            NaN                  NaN        NaN        t1       NaN
239  ITEM1107  BATCH10777      2022-04-30          3050.0         351.0        Factory A  unassigned           MC4970  Morning                1.0             NaN     41.02       32.57               614.93        MAT100       34761.38     8684.19        6298.34    49743.91          16.31       OP756    op75647@gmail.com        S946      SH8012           NaN            NaN                  NaN        NaN       NaN       NaN
247  ITEM1170  BATCH10042      2024-03-16          3713.0         124.0        Factory C       Priya           MC2086  Morning                0.0             NaN    420.95       -1.02                11.99        MAT300        4636.78     2439.17        5043.42    12119.37           3.26       OP863       op8637@ops.com        S583         NaN           NaN            NaN                  NaN        NaN       NaN       NaN
250  ITEM1161  BATCH10580      2024-02-14          4576.0         134.0        Factory A  unassigned  unknown Machine  Morning                NaN          Failed    338.58      196.76               180.92        MAT100       14671.33    12505.76        9269.91    36447.00           7.96       OP849  noemail@factory.com         NaN         NaN           NaN            NaN                  1.0        NaN       NaN       NaN
252  ITEM1166  BATCH10967      2022-02-24          4002.0         191.0  unknown factory  unassigned           MC5251  Morning                NaN             NaN     58.12       48.77               688.18       BADCODE        7470.42     3177.18       11648.90         NaN            NaN       OP118      op11883@ops.com         NaN         NaN           NaN            NaN                  0.0        NaN        t1       NaN
275  ITEM1071  BATCH11822      2024-03-07          4002.0         303.0        Factory A  unassigned           MC4951  Morning                1.0             NaN    268.24      327.96               695.87        MAT100       46237.64     9790.99       14883.85         NaN            NaN       OP438      op43830@ops.com        S384         NaN           NaN            NaN                  NaN        NaN       NaN       NaN
282  ITEM1067  BATCH11917      2023-08-12          4002.0          84.0        Factory B       Kumar  unknown Machine  Morning                NaN          Failed    234.50      288.01               742.20        MAT300       29405.24     8987.44       14273.17         NaN            NaN       OP421    op42142@gmail.com        S561         NaN           NaN            NaN                  0.0        NaN        t1       NaN
287  ITEM1018  BATCH10658      2023-09-09          4002.0         456.0        Factory C       Priya           MC9810  Morning                NaN          Passed    410.22       61.14               987.09       BADCODE        6623.22      901.75        4886.00         NaN            NaN       OP936    op93699@gmail.com         NaN         NaN           NaN            NaN                  NaN      debug       NaN       NaN
306  ITEM1194  BATCH10996      2022-08-30          3764.0          20.0        Factory C         Anu           MC3388  Morning                NaN          Failed    227.13      173.31               849.97        MAT400       10359.97     5935.25        7467.86    23763.08           6.31       OP760      op76038@ops.com        S966         NaN           NaN            NaN                  NaN        NaN       NaN       NaN
314  ITEM1188  BATCH11577      2020-01-29          3853.0         226.0        Factory A       Priya           MC9361  Morning                1.0          Failed    225.09      456.93               185.03       mat-500       29435.58     7841.34        1810.63    39087.55          10.14       OP305  op30593@factory.com        S592         NaN          RC56            NaN                  NaN        NaN        t1       NaN
593  ITEM1000  BATCH11715      2025-03-27          4002.0         472.0        Factory C       Kumar           MC1057  Morning                0.0             NaN    242.03      114.08               645.73       mat-500       28207.13     3119.48        3520.21         NaN            NaN       OP279  op27941@factory.com         NaN         NaN          RC96            NaN                  1.0      debug       NaN       NaN
630  ITEM1066  BATCH10088      2025-01-04           912.0         161.0        Factory C  unassigned           MC8548  Morning                0.0             NaN    430.26      376.02               887.80        MAT400       31482.09    13364.71        7826.46    52673.26          57.76       OP589      op58942@ops.com        S594         NaN           NaN            NaN                  NaN      debug       NaN       NaN
673  ITEM1132  BATCH11842      2022-08-31          4430.0         152.0        Factory B       Kumar           MC6007  Morning                1.0             NaN    184.58      113.59                11.89           NaN       12579.05     2728.38        7336.28    22643.71           5.11         NaN           89@ops.com        S617         NaN           NaN            NaN                  1.0        NaN       NaN       NaN
685  ITEM1108  BATCH10981      2022-03-15          1202.0         375.0        Factory B       Priya           MC2486  Morning                1.0             NaN     76.71      228.56               570.38       BADCODE         245.09     9096.82       11577.53    20919.44          17.40       OP515    op51581@gmail.com         NaN         NaN           NaN            NaN                  NaN      debug        t1        t2
701  ITEM1074  BATCH10401      2022-03-15          4002.0          62.0  unknown factory  unassigned           MC2244  Morning                0.0          Failed    342.75      115.59               432.89        MAT300        2367.54    16257.52        8459.42         NaN            NaN       OP873  op87363@factory.com         NaN         NaN           NaN            NaN                  NaN      debug        t1        t2
755  ITEM1069  BATCH11491      2024-05-10          4002.0         147.0  unknown factory       Priya  unknown Machine  Morning                NaN          Passed    278.56      383.53               787.05        MAT100        2030.96     6751.83       14601.78         NaN            NaN       OP701    op70193@gmail.com         NaN      SH6241          RC66          MT512                  NaN      debug       NaN       NaN

In [31]:
#10.Fetch products with repeated defect patterns
print(df.groupby('Item_ID')['Defect_Count'].value_counts())

Item_ID   Defect_Count
ITEM1000  472.0           1
ITEM1003  65.0            1
ITEM1005  47.0            1
ITEM1007  178.0           1
ITEM1008  85.0            1
                         ..
ITEM1193  313.0           1
ITEM1194  20.0            1
ITEM1196  288.0           1
ITEM1197  13.0            1
ITEM1198  436.0           1
Name: count, Length: 116, dtype: int64

In [32]:
#1.	Add Yield_Rate = (Units_Produced − Defect_Count) / Units_Produced
df['Yield_Rate']=(df['Units_Produced'] - df['Defect_Count'])/(df['Units_Produced'])
print(df['Yield_Rate'])

1       0.993503
2       0.896552
4       0.944345
5       0.886288
6       0.902049
          ...
685     0.688020
701     0.984508
722     0.963518
755     0.963268
1080    0.953273
Name: Yield_Rate, Length: 116, dtype: float64

In [33]:
#2.	Calculate Defect_Rate per batch.
s=df.groupby('Batch_ID')['Defect_Count'].value_counts().reset_index(name='Counts')
print(s)

       Batch_ID  Defect_Count  Counts
0    BATCH10019         442.0       1
1    BATCH10024         398.0       1
2    BATCH10026         192.0       1
3    BATCH10031         436.0       1
4    BATCH10037          65.0       1
..          ...           ...     ...
111  BATCH11927         203.0       1
112  BATCH11931          71.0       1
113  BATCH11933         170.0       1
114  BATCH11937         371.0       1
115  BATCH11985          70.0       1

[116 rows x 3 columns]

In [34]:
#3.	Extract Year & Month from Production_Date
df['year_month']=df['Production_Date'].dt.to_period('M')
print(df['year_month'])

1       2020-12
2       2020-08
4       2021-06
5       2023-11
6       2021-01
         ...
685     2022-03
701     2022-03
722     2022-08
755     2024-05
1080    2021-01
Name: year_month, Length: 116, dtype: period[M]

In [35]:
#6.	Calculate Throughput = Units_Produced / Production_Duration.
df['Throughput']=df['Units_Produced']/df['Production_Duration']
print(df['Throughput'])

1       14.828263
2        4.702371
4        3.987329
5        3.768947
6       53.147410
          ...
685      2.107367
701      9.244843
722      4.717393
755      5.084810
1080     4.229058
Name: Throughput, Length: 116, dtype: float64

In [36]:
#7.	Create Shift_Flag for analysis.
df['shift_flag']=df['Shift'].map({'Afternoon':2,'Night':3,'Morning':1})
print(df['shift_flag'].value_counts())

shift_flag
3    39
2    39
1    38
Name: count, dtype: int64

In [37]:
#8.	Remove leading/trailing spaces
df=df.apply(lambda col:col.str.strip() if col.dtype=='object' else col)
df

,Item_ID,Batch_ID,Production_Date,Units_Produced,Defect_Count,Factory,Supervisor,Machine_ID,Shift,Quality_Fail_Flag,...,Root_Cause_ID,Maintenance_ID,Traceability_Record,Temp_Debug,Test_Col1,Test_Col2,Yield_Rate,year_month,Throughput,shift_flag
1,ITEM1181,BATCH10323,2020-12-31,4002.0,26.0,Factory A,unassigned,MC7084,Night,NaN,...,NaN,NaN,0.0,NaN,t1,NaN,0.993503,2020-12,14.828263,3
2,ITEM1036,BATCH11037,2020-08-01,4002.0,414.0,Factory C,unassigned,MC3719,Night,NaN,...,RC66,MT634,1.0,NaN,t1,NaN,0.896552,2020-08,4.702371,3
4,ITEM1186,BATCH11011,2021-06-29,2228.0,124.0,unknown factory,Priya,MC5216,Morning,NaN,...,NaN,MT738,0.0,debug,NaN,NaN,0.944345,2021-06,3.987329,1
5,ITEM1020,BATCH11244,2023-11-17,1196.0,136.0,Factory C,unassigned,MC1969,Afternoon,NaN,...,NaN,NaN,1.0,NaN,t1,NaN,0.886288,2023-11,3.768947,2
6,ITEM1033,BATCH10604,2021-01-20,4002.0,392.0,Factory A,unassigned,MC5210,Morning,1.0,...,NaN,NaN,0.0,NaN,t1,NaN,0.902049,2021-01,53.147410,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,ITEM1108,BATCH10981,2022-03-15,1202.0,375.0,Factory B,Priya,MC2486,Morning,1.0,...,NaN,NaN,NaN,debug,t1,t2,0.688020,2022-03,2.107367,1
701,ITEM1074,BATCH10401,2022-03-15,4002.0,62.0,unknown factory,unassigned,MC2244,Morning,0.0,...,NaN,NaN,NaN,debug,t1,t2,0.984508,2022-03,9.244843,1
722,ITEM1079,BATCH11688,2022-08-09,4002.0,146.0,Factory A,Ramesh,MC4379,Night,NaN,...,NaN,MT414,1.0,NaN,NaN,NaN,0.963518,2022-08,4.717393,3
755,ITEM1069,BATCH11491,2024-05-10,4002.0,147.0,unknown factory,Priya,unknown Machine,Morning,NaN,...,RC66,MT512,NaN,debug,NaN,NaN,0.963268,2024-05,5.084810,1
1080,ITEM1041,BATCH10473,2021-01-16,4002.0,187.0,Factory B,unassigned,MC8812,Night,1.0,...,RC43,MT870,NaN,NaN,NaN,NaN,0.953273,2021-01,4.229058,3

In [38]:
#9.	Flag runs with missing mandatory QC checks.
df['qc_missing']=df['QC_Check_Status'].isna()
print(df[['qc_missing','QC_Check_Status']])

      qc_missing QC_Check_Status
1           True             NaN
2          False          Passed
4          False          Failed
5          False          Failed
6           True             NaN
...          ...             ...
685         True             NaN
701        False          Failed
722         True             NaN
755        False          Passed
1080        True             NaN

[116 rows x 2 columns]

In [39]:
#10.Compute Cost_per_Unit from material + labor + overhead
df['cost_per_unit']=df['Material_Cost']+df['Labor_Cost']+df['Overhead_Cost']
print(df['cost_per_unit'])

1       56551.50
2       53547.87
4       15806.89
5       36202.77
6       76357.57
          ...
685     20919.44
701     27084.48
722     35227.25
755     23384.57
1080    74425.20
Name: cost_per_unit, Length: 116, dtype: float64

In [40]:
#1.	Top items by Units_Produced.
df['Units_Produced'].head(8)

1      4002.0
2      4002.0
4      2228.0
5      1196.0
6      4002.0
10    19556.0
11     4818.0
13     3577.0
Name: Units_Produced, dtype: float64

In [41]:
#2.	Batches with highest defect counts
l=df['Defect_Count'].max()
print(l)

493.0

In [42]:
#3.Average defect rate per factory.
print(df.groupby('Factory')['Defect_Count'].mean())

Factory
Factory A          214.090909
Factory B          132.812500
Factory C          177.650000
unknown factory    190.375000
Name: Defect_Count, dtype: float64

In [43]:
#4.	Machine-wise downtime totals.
print(df.groupby('Machine_ID')['Downtime'].sum())

Machine_ID
MC1009              129.08
MC1057              242.03
MC1059               27.92
MC1086              269.17
MC1166              249.11
                    ...
MC9810              410.22
MC9901              237.41
MC9968              492.88
MC9970               87.34
unknown Machine    2210.46
Name: Downtime, Length: 107, dtype: float64

In [44]:
#5.	Throughput per shift.
print(df.groupby('Shift')['Throughput'].sum())

Shift
Afternoon     414.136371
Morning      1744.276904
Night         835.919527
Name: Throughput, dtype: float64

In [45]:
#6.	Supervisor performance ranking by yield.
print(df.groupby('Supervisor')['Units_Produced'].sum())

Supervisor
Anu            65720.0
Kumar         195814.0
Priya          72060.0
Ramesh         65004.0
unassigned    182222.0
Name: Units_Produced, dtype: float64

In [46]:
#7.	Monthly production totals.
df['month']=df['Production_Date'].dt.month
print(df.groupby('month')['Units_Produced'].sum())

month
1     40656.0
2     56796.0
3     37170.0
4     17927.0
5     83052.0
6     31269.0
7     32798.0
8     58573.0
9     20268.0
10    99578.0
11    78691.0
12    24042.0
Name: Units_Produced, dtype: float64

In [47]:
#8.	Materials consumed per product.
print(df.groupby('Material_Code')['Material_Cost'].sum())

Material_Code
BADCODE    408833.97
MAT100     398337.27
MAT200     440543.89
MAT300     467734.07
MAT400     546620.60
mat-500    435680.66
Name: Material_Cost, dtype: float64

In [48]:
#9.	Count of quality fails per product.
fail_per_product=(df[df['QC_Check_Status'] == 'Failed']).groupby('Material_Code').size().reset_index(name='fail_Counts')
print(fail_per_product)

  Material_Code  fail_Counts
0       BADCODE            2
1        MAT100            5
2        MAT200            4
3        MAT300            3
4        MAT400            4
5       mat-500            5

In [49]:
#Total cost
df['Total_Cost']=df['Material_Cost']+df['Labor_Cost']+df['Overhead_Cost']

In [50]:
#cost per unit
df['Cost_per_Unit']=df['Total_Cost']/df['Units_Produced']

In [51]:
#10.Average cost_per_unit per product.
print(df.groupby('Material_Code')['cost_per_unit'].mean())

Material_Code
BADCODE    42017.973750
MAT100     34583.970000
MAT200     48180.350667
MAT300     43130.891053
MAT400     46231.690952
mat-500    43336.467778
Name: cost_per_unit, dtype: float64

In [52]:
#1.	Detect inconsistent Production_Date formats and standardize.
df['standardized_date']=df['Production_Date'].dt.strftime('%Y-%m-%d')

In [53]:
#2.	Validate Machine_ID formats and existence in master.
df['Machine_ID']
df

,Item_ID,Batch_ID,Production_Date,Units_Produced,Defect_Count,Factory,Supervisor,Machine_ID,Shift,Quality_Fail_Flag,...,Test_Col1,Test_Col2,Yield_Rate,year_month,Throughput,shift_flag,qc_missing,cost_per_unit,month,standardized_date
1,ITEM1181,BATCH10323,2020-12-31,4002.0,26.0,Factory A,unassigned,MC7084,Night,NaN,...,t1,NaN,0.993503,2020-12,14.828263,3,True,56551.50,12,2020-12-31
2,ITEM1036,BATCH11037,2020-08-01,4002.0,414.0,Factory C,unassigned,MC3719,Night,NaN,...,t1,NaN,0.896552,2020-08,4.702371,3,False,53547.87,8,2020-08-01
4,ITEM1186,BATCH11011,2021-06-29,2228.0,124.0,unknown factory,Priya,MC5216,Morning,NaN,...,NaN,NaN,0.944345,2021-06,3.987329,1,False,15806.89,6,2021-06-29
5,ITEM1020,BATCH11244,2023-11-17,1196.0,136.0,Factory C,unassigned,MC1969,Afternoon,NaN,...,t1,NaN,0.886288,2023-11,3.768947,2,False,36202.77,11,2023-11-17
6,ITEM1033,BATCH10604,2021-01-20,4002.0,392.0,Factory A,unassigned,MC5210,Morning,1.0,...,t1,NaN,0.902049,2021-01,53.147410,1,True,76357.57,1,2021-01-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,ITEM1108,BATCH10981,2022-03-15,1202.0,375.0,Factory B,Priya,MC2486,Morning,1.0,...,t1,t2,0.688020,2022-03,2.107367,1,True,20919.44,3,2022-03-15
701,ITEM1074,BATCH10401,2022-03-15,4002.0,62.0,unknown factory,unassigned,MC2244,Morning,0.0,...,t1,t2,0.984508,2022-03,9.244843,1,False,27084.48,3,2022-03-15
722,ITEM1079,BATCH11688,2022-08-09,4002.0,146.0,Factory A,Ramesh,MC4379,Night,NaN,...,NaN,NaN,0.963518,2022-08,4.717393,3,True,35227.25,8,2022-08-09
755,ITEM1069,BATCH11491,2024-05-10,4002.0,147.0,unknown factory,Priya,unknown Machine,Morning,NaN,...,NaN,NaN,0.963268,2024-05,5.084810,1,False,23384.57,5,2024-05-10
1080,ITEM1041,BATCH10473,2021-01-16,4002.0,187.0,Factory B,unassigned,MC8812,Night,1.0,...,NaN,NaN,0.953273,2021-01,4.229058,3,True,74425.20,1,2021-01-16

In [54]:
#3.	Detect duplicated batch entries.
print(df.duplicated(subset=['Batch_ID']).value_counts())

False    115
True       1
Name: count, dtype: int64

In [55]:
#5.	Validate material codes against master list
df['Material_Code']=df['Material_Code'].replace({'mat-500':'MAT500'})
for i in df.index:
    if df.loc[i,'Material_Code']=='BADCODE':
        df.drop(i,inplace=True)
print(df['Material_Code'].value_counts())

Material_Code
MAT400    21
MAT100    20
MAT300    19
MAT500    18
MAT200    15
Name: count, dtype: int64

In [56]:
#6.	Convert date columns to datetime and sort.
df['Production_Date']=pd.to_datetime(df['Production_Date'])

In [57]:
#7. Ensure no negative numeric values where impossible.

# Select only numeric columns for the comparison
numeric_cols = df.select_dtypes(include=np.number).columns

# Apply the condition only to numeric columns
df_no_neg = df.copy()
df_no_neg[numeric_cols] = df_no_neg[numeric_cols].where(df_no_neg[numeric_cols] >= 0, np.nan)

print(df_no_neg)

      Item_ID    Batch_ID Production_Date  Units_Produced  Defect_Count  \
1    ITEM1181  BATCH10323      2020-12-31          4002.0          26.0
2    ITEM1036  BATCH11037      2020-08-01          4002.0         414.0
4    ITEM1186  BATCH11011      2021-06-29          2228.0         124.0
5    ITEM1020  BATCH11244      2023-11-17          1196.0         136.0
6    ITEM1033  BATCH10604      2021-01-20          4002.0         392.0
..        ...         ...             ...             ...           ...
604  ITEM1011  BATCH10393      2022-10-18         12928.0         417.0
630  ITEM1066  BATCH10088      2025-01-04           912.0         161.0
673  ITEM1132  BATCH11842      2022-08-31          4430.0         152.0
701  ITEM1074  BATCH10401      2022-03-15          4002.0          62.0
755  ITEM1069  BATCH11491      2024-05-10          4002.0         147.0

             Factory  Supervisor       Machine_ID      Shift  \
1          Factory A  unassigned           MC7084      Night
2          Factory C  unassigned           MC3719      Night
4    unknown factory       Priya           MC5216    Morning
5          Factory C  unassigned           MC1969  Afternoon
6          Factory A  unassigned           MC5210    Morning
..               ...         ...              ...        ...
604        Factory A       Kumar           MC7640      Night
630        Factory C  unassigned           MC8548    Morning
673        Factory B       Kumar           MC6007    Morning
701  unknown factory  unassigned           MC2244    Morning
755  unknown factory       Priya  unknown Machine    Morning

     Quality_Fail_Flag  ... Test_Col1  Test_Col2  Yield_Rate  year_month  \
1                  NaN  ...        t1        NaN    0.993503     2020-12
2                  NaN  ...        t1        NaN    0.896552     2020-08
4                  NaN  ...       NaN        NaN    0.944345     2021-06
5                  NaN  ...        t1        NaN    0.886288     2023-11
6                  1.0  ...        t1        NaN    0.902049     2021-01
..                 ...  ...       ...        ...         ...         ...
604                1.0  ...        t1        NaN    0.967744     2022-10
630                0.0  ...       NaN        NaN    0.823465     2025-01
673                1.0  ...       NaN        NaN    0.965688     2022-08
701                0.0  ...        t1         t2    0.984508     2022-03
755                NaN  ...       NaN        NaN    0.963268     2024-05

     Throughput  shift_flag  qc_missing  cost_per_unit  month  \
1     14.828263           3        True       56551.50     12
2      4.702371           3       False       53547.87      8
4      3.987329           1       False       15806.89      6
5      3.768947           2       False       36202.77     11
6     53.147410           1        True       76357.57      1
..          ...         ...         ...            ...    ...
604   14.270576           3       False       56170.70     10
630    1.027258           1        True       52673.26      1
673  372.582002           1        True       22643.71      8
701    9.244843           1       False       27084.48      3
755    5.084810           1       False       23384.57      5

     standardized_date
1           2020-12-31
2           2020-08-01
4           2021-06-29
5           2023-11-17
6           2021-01-20
..                 ...
604         2022-10-18
630         2025-01-04
673         2022-08-31
701         2022-03-15
755         2024-05-10

[100 rows x 38 columns]

In [58]:
#9.	Standardize shift naming conventions.
print(df['Shift'].unique())

['Night' 'Morning' 'Afternoon']

In [59]:
#10.	Validate presence of mandatory QC checks before dispatch.
qc_pass=df[df['QC_Check_Status']=='Passed']
print(qc_pass.to_string())

      Item_ID    Batch_ID Production_Date  Units_Produced  Defect_Count          Factory  Supervisor       Machine_ID      Shift  Quality_Fail_Flag QC_Check_Status  Downtime  Cycle_Time  Production_Duration Material_Code  Material_Cost  Labor_Cost  Overhead_Cost  Total_Cost  Cost_per_Unit Operator_ID                Email Supplier_ID Shipping_ID Root_Cause_ID Maintenance_ID  Traceability_Record Temp_Debug Test_Col1 Test_Col2  Yield_Rate year_month  Throughput  shift_flag  qc_missing  cost_per_unit  month standardized_date
2    ITEM1036  BATCH11037      2020-08-01          4002.0         414.0        Factory C  unassigned           MC3719      Night                NaN          Passed     42.51      373.71               851.06        MAT300       44962.26      297.26        8288.35    53547.87      13.380277       OP872      op87281@ops.com        S994      SH6908          RC66          MT634                  1.0        NaN        t1       NaN    0.896552    2020-08    4.702371           3       False       53547.87      8        2020-08-01
20   ITEM1081  BATCH10738      2023-07-20          4002.0         147.0        Factory A       Kumar           MC8025    Morning                NaN          Passed     83.40      494.05               471.87        MAT300        3082.61     1260.62         184.81     4528.04       1.131444       OP255      op25550@ops.com         NaN         NaN           NaN          MT245                  NaN        NaN       NaN       NaN    0.963268    2023-07    8.481149           1       False        4528.04      7        2023-07-20
24   ITEM1010  BATCH10024      2020-06-01          3849.0         398.0        Factory A  unassigned           MC1009    Morning                0.0          Passed    129.08      240.30                66.09        MAT400       45671.84     3312.08       10089.18    59073.10      15.347649       OP785      op78579@ops.com         NaN         NaN           NaN            NaN                  0.0        NaN       NaN        t2    0.896597    2020-06   58.238765           1       False       59073.10      6        2020-06-01
53   ITEM1003  BATCH10037      2021-12-17          4032.0          65.0        Factory A      Ramesh           MC4155  Afternoon                1.0          Passed    166.66       14.73               838.85        MAT100       34438.79    17863.69        5086.55    57389.03      14.233390       OP827      op82767@ops.com         NaN         NaN          RC85          MT749                  1.0      debug       NaN       NaN    0.983879    2021-12    4.806580           2       False       57389.03     12        2021-12-17
78   ITEM1130  BATCH10101      2022-05-05          2789.0         177.0        Factory A       Kumar  unknown Machine    Morning                0.0          Passed     46.20      495.73               128.54        MAT100       10809.35      438.07        5930.19    17177.61       6.159057       OP605  op60510@factory.com         NaN         NaN           NaN          MT614                  0.0        NaN       NaN       NaN    0.936536    2022-05   21.697526           1       False       17177.61      5        2022-05-05
90   ITEM1075  BATCH11879      2020-07-31          3851.0         172.0  unknown factory       Kumar           MC7579      Night                1.0          Passed    333.50      260.39               917.19        MAT400       31298.39     5581.49        5085.98    41965.86      10.897393       OP497  op49795@factory.com         NaN         NaN          RC32            NaN                  1.0        NaN        t1       NaN    0.955336    2020-07    4.198694           3       False       41965.86      7        2020-07-31
111  ITEM1027  BATCH11016      2024-05-14          2333.0           9.0        Factory A  unassigned           MC3549      Night                NaN          Passed    359.49      127.70               581.83        MAT300       42115.45    12722.65       12322.13    67160.23      28.787068       OP473  op47310@factory.com         NaN         NaN          RC77          MT823                  1.0        NaN       NaN       NaN    0.996142    2024-05    4.009762           3       False       67160.23      5        2024-05-14
114  ITEM1092  BATCH11197      2020-06-11          1904.0         250.0        Factory C  unassigned           MC3376      Night                0.0          Passed     93.04      317.53               475.30           NaN       26594.67     3286.33        4951.47    34832.47      18.294364       OP714      op71418@ops.com         NaN         NaN          RC11            NaN                  1.0        NaN        t1       NaN    0.868697    2020-06    4.005891           3       False       34832.47      6        2020-06-11
150  ITEM1183  BATCH11826      2020-09-26          4002.0         146.0        Factory C       Kumar           MC8550  Afternoon                NaN          Passed     44.79      179.17               849.42        MAT200       34785.95    17994.71        4576.44    57357.10      14.332109       OP871      op87171@ops.com         NaN      SH8434          RC10            NaN                  1.0      debug       NaN       NaN    0.963518    2020-09    4.711450           2       False       57357.10      9        2020-09-26
228  ITEM1196  BATCH11409      2020-06-18          3275.0         288.0        Factory A       Kumar           MC5452  Afternoon                1.0          Passed    161.93      229.71               271.46        MAT100       16391.38      235.98        2109.40    18736.76       5.721148       OP437  noemail@factory.com         NaN         NaN           NaN            NaN                  NaN      debug       NaN        t2    0.912061    2020-06   12.064393           2       False       18736.76      6        2020-06-18
336  ITEM1100  BATCH10412      2023-08-24           750.0          92.0        Factory C  unassigned           MC3624  Afternoon                0.0          Passed     88.62      193.87               498.37        MAT300        -882.23    13802.62       12498.45    25418.84      33.891787       OP452    op45216@gmail.com         NaN         NaN           NaN          MT194                  0.0      debug        t1       NaN    0.877333    2023-08    1.504906           2       False       25418.84      8        2023-08-24
385  ITEM1113  BATCH10985      2024-05-29          4002.0         448.0        Factory A      Ramesh           MC2246  Afternoon                NaN          Passed    316.01      397.25               550.12        MAT500       36476.38     6992.79         167.85    43637.02      10.903803       OP216  noemail@factory.com        S370      SH9274          RC28          MT335                  NaN      debug       NaN       NaN    0.888056    2024-05    7.274776           2       False       43637.02      5        2024-05-29
391  ITEM1198  BATCH10031      2021-04-21          4002.0         436.0        Factory A  unassigned           MC9089      Night                NaN          Passed    183.21      426.10               397.51        MAT400       25134.71    14141.12         189.86    39465.69       9.861492       OP860  op86090@factory.com        S296         NaN           NaN            NaN                  0.0        NaN       NaN       NaN    0.891054    2021-04   10.067671           3       False       39465.69      4        2021-04-21
604  ITEM1011  BATCH10393      2022-10-18         12928.0         417.0        Factory A       Kumar           MC7640      Night                1.0          Passed    421.85      166.05               905.92        MAT200       29567.96    16268.12       10334.62    56170.70       4.344887       OP696    op69624@gmail.com        S533         NaN           NaN            NaN                  1.0        NaN        t1       NaN    0.967744    2022-10   14.270576           3       False       56170.70     10        2022-10-18
755  ITEM1069  BATCH11491      2024-05-10          4002.0         147.0  unknown factory       Priya  unknown Machine    Morning                NaN          Passed    278.56      383.53               787.05        MAT100        2030.96     6751.83       14601.78    23384.57       5.843221       OP701    op70193@gmail.com         NaN      SH6241          RC66          MT512                  NaN      debug       NaN       NaN    0.963268    2024-05    5.084810           1       False       23384.57      5        2024-05-10

In [60]:
df['Quality_Fail_Flag']=df['Quality_Fail_Flag'].fillna(0)

In [61]:
df['QC_Check_Status']=df['QC_Check_Status'].fillna('not check')

In [62]:
df['Material_Code']=df['Material_Code'].fillna('unknown')

In [63]:
import numpy as np
import pandas as pd

# Replace negative numeric values with 0, preserving all columns
df[df.select_dtypes(include=np.number).columns] = df.select_dtypes(include=np.number).clip(lower=0)

print(df.head())

    Item_ID    Batch_ID Production_Date  Units_Produced  Defect_Count  \
1  ITEM1181  BATCH10323      2020-12-31          4002.0          26.0
2  ITEM1036  BATCH11037      2020-08-01          4002.0         414.0
4  ITEM1186  BATCH11011      2021-06-29          2228.0         124.0
5  ITEM1020  BATCH11244      2023-11-17          1196.0         136.0
6  ITEM1033  BATCH10604      2021-01-20          4002.0         392.0

           Factory  Supervisor Machine_ID      Shift  Quality_Fail_Flag  ...  \
1        Factory A  unassigned     MC7084      Night                0.0  ...
2        Factory C  unassigned     MC3719      Night                0.0  ...
4  unknown factory       Priya     MC5216    Morning                0.0  ...
5        Factory C  unassigned     MC1969  Afternoon                0.0  ...
6        Factory A  unassigned     MC5210    Morning                1.0  ...

  Test_Col1  Test_Col2  Yield_Rate  year_month Throughput  shift_flag  \
1        t1        NaN    0.993503     2020-12  14.828263           3
2        t1        NaN    0.896552     2020-08   4.702371           3
4       NaN        NaN    0.944345     2021-06   3.987329           1
5        t1        NaN    0.886288     2023-11   3.768947           2
6        t1        NaN    0.902049     2021-01  53.147410           1

   qc_missing  cost_per_unit  month  standardized_date
1        True       56551.50     12         2020-12-31
2       False       53547.87      8         2020-08-01
4       False       15806.89      6         2021-06-29
5       False       36202.77     11         2023-11-17
6        True       76357.57      1         2021-01-20

[5 rows x 38 columns]

In [64]:
df['Operator_ID'] = df['Operator_ID'].fillna(method='ffill')

/tmp/ipykernel_515/604320301.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Operator_ID'] = df['Operator_ID'].fillna(method='ffill')

In [65]:
import random
l=['t1','unknown']
df['Test_Col1'] = df['Test_Col1'].apply(lambda x:random.choice(l) if pd.isna(x) else x)
print(df['Test_Col1'])

1           t1
2           t1
4           t1
5           t1
6           t1
        ...
604         t1
630    unknown
673    unknown
701         t1
755    unknown
Name: Test_Col1, Length: 100, dtype: object

In [66]:
l=['t2','unknown']
df['Test_Col2'] = df['Test_Col2'].apply(lambda x:random.choice(l) if pd.isna(x) else x)

In [67]:
l=['debug','unknown']
df['Temp_Debug'] = df['Temp_Debug'].apply(lambda x:random.choice(l) if pd.isna(x) else x)

In [68]:
df['Traceability_Record'] = df['Traceability_Record'].fillna(method='bfill')

/tmp/ipykernel_515/1308162694.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Traceability_Record'] = df['Traceability_Record'].fillna(method='bfill')

In [69]:
l=['MT634','MT245','MT681','unknown','MT364','MT103']
df['Maintenance_ID'] = df['Maintenance_ID'].apply(lambda x:random.choice(l) if pd.isna(x) else x)

In [70]:
l=['RC66','RC18','RC80','RC74','unknown','RC97']
df['Maintenance_ID'] = df['Maintenance_ID'].apply(lambda x:random.choice(l) if pd.isna(x) else x)

In [71]:
import random
import pandas as pd
l=['SH8023','SH2774','SH6882','unknown','SH5169','SH1177']
df['Shipping_ID'] = df['Shipping_ID'].apply(lambda x: random.choice(l) if pd.isna(x) else x)

In [72]:
l=('S994','S903','unknown','S103','S173','S821')
df['Supplier_ID'] = df['Supplier_ID'].apply(lambda x:random.choice(l) if pd.isna(x) else x)

In [73]:
l=('RC66','RC33','RC80','unknown','RC96')
df['Root_Cause_ID'] = df['Root_Cause_ID'].apply(lambda x:random.choice(l) if pd.isna(x) else x)

In [74]:
#sort shift columns
df.sort_values(by='shift_flag',inplace=True)
df.reset_index(drop=True,inplace=True)

In [75]:
df=df.drop(columns=['month'])

In [76]:
#df.to_excel('/content/P1.xlsx',index=False)